package portailEV3.enumeration;

public enum EtatPortail {
	
	EN_OUVERTURE_TOTALE,
	EN_OUVERTURE_PARTIELLE,
	EN_FERMETURE_TOTALE,
	EN_FERMETURE_PARTIELLE,
	FERME,
	OUVERT,
	OUVERT_PARTIELLEMENT,
	ARRETE_EN_FERMETURE,
	ARRETE_EN_OUVERTURE,
	ARRETE_EN_OUVERTURE_PARTIELLE,
	INCONNU

}